on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          echo $JAVA_HOME_17_X64
          export JAVA_HOME=$(echo $JAVA_HOME_17_X64)
          export PATH=/opt/java/jdk-17.0.2/bin:$PATH
          export PATH=/opt/maven/apache-maven-3.9.6/bin/:$PATH
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=aem-test -Dsonar.projectName='aem-test'
