name: test_poc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MAVEN_HOME: ${{ secrets.MAVEN_HOME }}
  SONARSCANNER: ${{ secrets.SONARSCANNER }}
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
      - name: Checking out
        uses: actions/checkout@v2
            # Setup java 17 to be default (sonar-scanner requirement as of 5.x)
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Maven
        run: |
          export PATH=$MAVEN_HOME/bin/:$PATH
        
      - name: Setup Sonar Scan
        run: |
          
          export PATH=/opt/sonarscanner/sonar-scanner-4.8.0.2856-linux/bin/:$PATH
      - name: SonarQube Scan
        run: |
          export PATH=/opt/maven/apache-maven-3.9.6/bin/:$PATH
          export PATH=/opt/sonarscanner/sonar-scanner-4.8.0.2856-linux/bin/:$PATH
          sonar-scanner
          mvn clean verify sonar:sonar -Dsonar.projectKey=aem-test1 -Dsonar.projectName='aem-test1' -Dsonar.host.url=http://15.207.87.74:9000 -Dsonar.token=sqp_e4bea137a03c5f15c821c6b505010f62eaba91b2
        
