name: test_poc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Setup Java Development Kits built by Oracle
        uses: oracle-actions/setup-java@v1.3.3
        with:
          release: 17
          version: 17
          install: true

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Sonar Scan
        uses: sijomc/sonarscan-action@1.1
        with:
          host: http://15.207.87.7
          login: sqa_e286f9c1e4a5cc63b1ece9332f385b81cb057822
