name: test_poc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
      - name: Checking out
        uses: actions/checkout@v2
            # Setup java 17 to be default (sonar-scanner requirement as of 5.x)
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Sonar Scan
        uses: warchant/setup-sonar-scanner@v7
      - name: SonarQube Scan
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=aem-test1 -Dsonar.projectName='aem-test1' -Dsonar.host.url=http://15.207.87.74:9000 -Dsonar.token=sqp_e4bea137a03c5f15c821c6b505010f62eaba91b2
        
